name: Train Model

on:
  push:
    paths:
      - train_model.py
      - preprocess.py

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python train_model.py

      - name: Run tests
        run: pytest
